name: 'Setup SLSA Verifier'
description: 'Downloads the vendored SLSA Verifier binary and adds it to the GITHUB_PATH'

runs:
  using: 'composite'
  steps:
    - name: Add SLSA Verifier to PATH
      shell: bash
      run: |
        (cd ${{ github.action_path }} && ./run.sh extract)
        echo "${{ github.action_path }}/linux/amd64/bin" >> $GITHUB_PATH
        chmod +x ${{ github.action_path }}/linux/amd64/bin/slsa-verifier
        (set +e +o pipefail; ${{ github.action_path }}/linux/amd64/bin/slsa-verifier version --json || true)

    - name: debug
      shell: bash
      if: failure()
      continue-on-error: true
      run: |-
        sudo apt install -y tree
        (set -x; echo ${{ github.action_path }}; tree ${{ github.action_path }})
