name: Test - Setup Action
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - setup-*/*.yml
      - setup-*/*.yml
      - setup-*/*.sh
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: repo
      - name: run action
        uses: ./repo/setup-yq

      - name: check executable
        shell: bash
        run: yq --help